### ISSUE TITLE
Update to progressbar broke ppbench

### ISSUE THREAD

**Issue by Kuzmin** [nkratzke/pingpong#6]
Hello!

An update to the `progressbar` gem seems to have broken `ppbench` for us. My suggested fix would be to lock the version in the gemspec. Would you accept a PR for this?

It would also be nice to lock down all the other dependencies at the same time, to avoid `ppbench` breaking randomly in the future.

**Comment by nkratzke** [comment]
Yes, good idea. I would Welcome your PR.

**Comment by Kuzmin** [comment]
Thank you for the prompt reply! Just uploaded a PR

**Comment by nkratzke** [comment]
Should be done with commit 7e3404bc33039f5b5284a7a22c8b514b3ae35cce

**Comment by Kuzmin** [comment]
Thanks for quick turnaround!
